### ISSUE TITLE
Please add python3 support

### ISSUE THREAD

**Issue by wt** [0xGiddi/pymbr#1]
Please add python3 support.

One issue I have identified is the use of xrange in the partition.py file. On way to work around this would be to use range despite it being less great in python2. Another would be to utilize something like the six lib and use a construct from that.

**Comment by 0xGiddi** [comment]
Ill take a look into it as soon as possible to make the project Python 3 compatible. Probably will be done with the builtin `range` to minimize needed 3rd party modules.

**Comment by 0xGiddi** [comment]
Not a good fix, overall the whole thing can be coded better. But it dose the job for now.
